services:
  postgres:
    container_name: postgres-sql-todo-list
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: todo_list
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - todo-list-network
    restart: unless-stopped

networks:
  todo-list-network:
    driver: bridge

volumes:
  postgres:
    driver: local